### ISSUE TITLE
Rewrite api's to use POST/PUT/PATCH/DELETE

### ISSUE THREAD

**Issue by galadril** [WLANThermo-nano/WLANThermo_ESP32_Software#112]
Currently /setchannels, /setsystem, etc only support POST. Then we have to supply the complete json payload instead of partial updates.

Please look into adding PATCH, were you could partially update your system or channels
![image](https://user-images.githubusercontent.com/14561640/90817664-6b837700-e32e-11ea-800b-386f68c8f6b6.png)

![image](https://user-images.githubusercontent.com/14561640/90817847-8229ce00-e32e-11ea-8df9-947ec7a12839.png)

**Comment by galadril** [comment]
So the correct implementation of an api should be:

POST > full json payloads (adds an item to the list)..  (!not updating data!)
PUT > full json payload, updates items (!not adding new data!)
PATCH > partial json payload, updates items (!not adding new data!)
DELETE > deletes an item from the api

more info here:
https://jsonplaceholder.typicode.com/

**Comment by Phantomias2006** [comment]
not planned
