### ISSUE TITLE
Schreibfehler im Menupunkt System

### ISSUE THREAD

**Issue by arminth** [WLANThermo-nano/WLANThermo_ESP32_Software#137]
Da steht 

Beta-Versionen in der Suche mit **einschießen** 

Grüßle
der Papa

**Comment by Phantomias2006** [comment]
Sehr geehrter Herr arminth, vielen Dank für Ihren Bug Report. Ich werde Ihr Ticket schließen da dieser Bug bereits vor 20min gefixt wurde.

**Comment by arminth** [comment]
Sehr geehrtes Flöhchen,
und weil ich mich schon gewundert habe, wo mein issüü hin is, hab ich es gleich nochmal aufgemacht! Muuuuhahaaa!

Leibe Grüße vom BABA
