### ISSUE TITLE
possibility to connect to hidden wifi

### ISSUE THREAD

**Issue by mark77-DE** [WLANThermo-nano/WLANThermo_ESP32_Software#157]
Feature request:

Is it possible to add the possibility to connect to hidden wifi networks?

Regards,
Mark

**Comment by sochs** [comment]
Die Verbindung zu einem versteckten Netzwerk ist möglich. Dafür muss dieses bei der Ersteinrichtung nur temporär sichtbar gemacht werden. Danach kann sich das Thermo auch mit dem bekannten Netzwerk mit versteckter SSID verbinden. 
Mal davon abgesehen, dass das verstecken einer SSID nur in den wenigsten Fällen überhaupt einen Nutzen hat.
