### ISSUE TITLE
Broken handling of cloud graph when switching between Celsius/Fahrenheit during ongoing measurement

### ISSUE THREAD

**Issue by ktetzlaff** [WLANThermo-nano/WLANThermo_ESP32_Software#160]
Observed behavior: When switching the temperature measurement unit (Celsius/Fahrenheit) during an ongoing measurement, the changed values are displayed in the new unit but the unit of the graph itself doesn't change (and already received values are still displayed with their value in the previously selected measurement unit). Example: Cloud measurement session gets started with measurement unit Celsius and temperature value of 100 C. When switching the unit to Fahrenheit, the temperature values suddenly jump from 100 to 212 but the graph still shows a measurement unit of C and already recorded values are still shown as 100.

Expected behavior: Show all values in one measurement unit.

Here are some ideas on how to implement this:

1. Keep the initially set measurement unit in the cloud graph and recalculate received values in different unit before displaying them.
2. When switching the measurement unit on the device, also switch the graph measurement unit and recalculate previously received values.
3. Allow the user to select the cloud measurement unit independent from the device.
4. A combination of 2/3: Follow the measurement unit configured in the device but allow user to override cloud measurement unit.

**Comment by sochs** [comment]
Very theoretical use case. The unit primarily only adjusted once. 

@tuniii lass uns beim Wechsel der Unit einen neuen Token generieren. Einfach und sicher. Niemand wird während eines normalen Betriebs mehrfach die Unit wechseln.
