### ISSUE TITLE
Autotune is possibly broken

### ISSUE THREAD

**Issue by tuniii** [WLANThermo-nano/WLANThermo_ESP32_Software#22]

**Comment by sochs** [comment]
Autotune würde ich erstmal zurückstellen. Das Feld sollten wir im Webinterface einfach erstmal ausgrauen, sodass der Autotune nicht gewählt werden kann. Den Autotune würde ich dann neu aufbauen.

**Comment by Phantomias2006** [comment]
@sochs / @tuniii - kann dieses Ticket geschlossen werden?

**Comment by tuniii** [comment]
Currently not planned for ESP32.
