### ISSUE TITLE
Recovery Mode Presentation on Nextion

### ISSUE THREAD

**Issue by sochs** [WLANThermo-nano/WLANThermo_ESP32_Software#31]
Wäre gut, wenn wir am Nextion noch ein "Baustellenfoto" hätten, was während des Recovery Mode erscheint. Vielleicht in Anlehnung an ein Baustellen-Schild im Straßenverkehr (Bauarbeiter mit Schippe und Sandhaufen) eine Figur, die mit Grillzange am Grill steht, weiß auf grauem Hintergrund, und darunter "Recovery Mode". Falls sich jemand künstlerisch betätigen möchste. Ansonsten wir ein reines "Recovery Mode", weiß auf grau, auch schonmal gut.

**Comment by tuniii** [comment]
Ich würde die Anzeige, dann aber nur beim Recovery-Mode aus der App raus machen und dabei die Nextion-Seite von der App aus laden. Ich würde das Nextion ungern aus dem Recocery Mode ansteuern, außer zum Flashen. Beim Recovery-Mode über den Taster würde die Seite dann nicht angezeigt werden.

**Comment by sochs** [comment]
Ich hatte folgenden Fall. Ich habe den Nextion FileUpload im Recovery Mode getestet. Display wurde ordentlich neu installiert und startet danach dann mit dem Startbildschirm. Dabei bleibt es. Im ersten Moment dachte ich, es wäre was falsch gelaufen. Das Webinterface habe ich nicht gesehen, weil die FileUploadSeite offen war. Erst als ich wieder zur IP gewechselt bin und gesehen habe, dass ich noch im Recovery Mode bin, wurde mir klar, warum am Nextion nix passiert. Könnte mir vorstellen, dass das zu Verwirrung führt. Aber vielleicht können wir da auch anders etwas Klarheit reinbringen. 

Kannst du von der FileUpload-Page wieder zurück auf die IP leiten. Oder wir machen nach einem Nextion Update immer einen Restart des ESP, sodass man dann wieder im offiziellen Mode ist. 

Das mit dem Nextion nicht ansprechen im Recovery Mode sehe ich ein. Ein Unterschied zwischen von App starten und über die Tasten würde ich dann aber auch nicht unbedingt machen. Dann besser nix.

**Comment by tuniii** [comment]
Bei der Seite vom Recovery Mode ist noch ziemlich Luft nach oben. Ich stelle mir da auch einen Ladebalken beim Flashen vor. Die Seite soll dabei auch ständig angezeigt werden. Damit sieht man dann auch nach dem Flashen, dass man noch im Recovery Mode ist. Den Recovery Mode muss man selbstständig verlassen, da es ja sein kann, dass man sowohl Firmware als auch Nextion flashen will.

**Comment by tuniii** [comment]
Recovery Mode hat nun eine neue Oberfläche. Nextion wird absichtlich nicht angesteuert. Ticket wird geschlossen.
