### ISSUE TITLE
Deactivate Channel Function

### ISSUE THREAD

**Issue by sochs** [WLANThermo-nano/WLANThermo_ESP32_Software#32]
Wollen wir eine Deaktivierungsfunktion für einen Kanal einbauen? Also ein Kontrollkästchen in den Kanaleinstellungen jedes Kanals, mit dem ein Kanal aus der dynamischen Darstellung der Kanäle entfernt wird, auch wenn ein Fühler angeschlossen ist. Ist an keinem Kanal ein Fühler angeschlossen, ist er dennoch sichtbar als OFF-Kanal. Sonst kann man ihn ja nicht mehr ändern.

**Comment by Phantomias2006** [comment]
@sochs / @tuniii Ich denke wir brauchen diese Funktion nicht. Kann das Ticket geschlossen werden oder soll das Feature umgesetzt werden?

**Comment by tuniii** [comment]
Currently not planned for ESP32.
