### ISSUE TITLE
Change Authentication pop-up name

### ISSUE THREAD

**Issue by sochs** [WLANThermo-nano/WLANThermo_ESP32_Software#56]
Aktuell wird beim Aufpoppen der Authentifizierung am Webinterface der Name "asyncesp" angezeigt. Das sollte zu "WLANThermo" oder ähnlichem geändert werden (muss nochmal schauen, was beim Nano aktuell kommt). Dafür muss die Webserver Lib modifiziert werden.

**Comment by tuniii** [comment]
New realm name: "WLANThermo Device"
