### ISSUE TITLE
Erweiterung des device objects 

### ISSUE THREAD

**Issue by Phantomias2006** [WLANThermo-nano/WLANThermo_ESP32_Software#6]
das Device Object muss um folgende Parameter erweitert werden:

`  "device": {
    "device": "mini",
    "serial": "xxxxxx",
    "**cpu**": "esp32",
    "**flash_size**": "33554432",
    "hw_version": "v1",
    "sw_version": "v1.0.0"
  }`
cpu -> esp32/esp82xx
flash_size -> int [bytes]

**Comment by tuniii** [comment]
Solved with commit 7298baa.
