### ISSUE TITLE
Input Keyboard is missing underscore sign

### ISSUE THREAD

**Issue by arminth** [WLANThermo-nano/WLANThermo_ESP32_Software#65]
When trying to enter a WLAN password via the display, there is no "_"-sign. Tapping on CAPS in numeric-mode leads to CAPS-alphabet-mode. Would be better to lead to extended special-character-numeric-mode.

**Comment by lemuba** [comment]
I suppose that this can be closed.

To get the underscore sign ____ push the CAPS button...

**Comment by tuniii** [comment]
Solved since v1.0.6

**Comment by ImagineTitanz** [comment]
I'm on Nextion Editor V1.61.2, and the full qwerty\keybdA option doesn't have "_" (underscore sign), can you help me if I'm picking the wrong keyboard or so?

**Comment by tuniii** [comment]
The keybdA, which comes with the Nextion Editor, does not have the underscore sign. But you can unlock the page and add it yourself or you could just simply export the page from our Nextion project: [miniVx.HMI](https://github.com/WLANThermo-nano/WLANThermo_ESP32_Software/blob/master/nextion/miniVx.HMI)

**Comment by ImagineTitanz** [comment]
I have exported and imported your page to my project it was imported with the name "keybdA0" if you could help me know how could I make it an option to select your keyboard in the .key attribute I'll be very glad.
![image](https://user-images.githubusercontent.com/33972553/104496118-2b06ed00-559e-11eb-86ce-7bccd467dc64.png)

**Comment by tuniii** [comment]
It seems like the page name is reserved for the original keyboard. You can also modify the original keyboard. Just unlock it, go to refshow and adapt the code for the "Touch Release Event". You can also copy over the code from the imported one.
![image](https://user-images.githubusercontent.com/23635855/104498538-18aba400-55dc-11eb-9a06-741fef292087.png)

**Comment by I8NHJ** [comment]
The page is password protected, how can be unlocked?
