### ISSUE TITLE
prerelease in den Settings aufnehmen

### ISSUE THREAD

**Issue by Phantomias2006** [WLANThermo-nano/WLANThermo_ESP32_Software#7]
Zukünftig soll der User selber die möglichkeit haben zu entscheiden ob er prereleases installieren möchte oder nicht. Dazu müssen folgende Änderungen durchgeführt werden:

- [x]  Erweiterung der settings API
`    "system": {
        "time": "1546271847",
        "unit": "C",
        "ap": "NANO-AP",
        "host": "NANO-84b3ec",
        "language": "de",
        "version": "v1.0.3",
        "getupdate": "false",
        "autoupd": true,
        "prerelease":true,
        "hwversion": "V1",
        "god": 0
    }`
Im system object muss folgender Parameter ergänzt werden:
prerelease -> boolean

- [x] Erweiterung des update objects (cloud api)
`    "update": {
	"prerelease": true
  }`
Im update object muss folgender Parameter ergänzt werden:
prerelease-> boolean

- [x] Anzeige im Frontend

**Comment by tuniii** [comment]
Solved with 89dc143.
