### ISSUE TITLE
Manual Pitmaster Value not shown in GUI

### ISSUE THREAD

**Issue by arminth** [WLANThermo-nano/WLANThermo_ESP32_Software#70]
(and not on Nextion but this we know already).

KwT

**Comment by sochs** [comment]
Ist auch erstmal nicht vorgesehen, da die Pitmasteranzeige an den entsprechenden (Isttemperatur-) Kanal gekoppelt ist und es diesen nur im "auto" Mode gibt. Der Einsatz des "manual" Modes beschränkt sich primär auf Aktortests / Grenzwertanalyse etc., wird also vermutlich nie längere Zeit aktiv sein. Aus diesen Grund haben wir uns schon beim Nano dagegen entschieden, auch hier den Pitmaster anzuzeigen. Dafür müsste man den Pitmaster wieder vom Kanal trennen, wie es beim Mini mit Pi bisher war. Ich lass den Issue nochmal offen, falls hier größere Einwände kommen, dann müsste man nochmal drüber nachdenken, wie man das geschickt abbilden könnten. Ansonsten würde ich das Issue dann schließen.
