### ISSUE TITLE
Web Interface Safety Issue showing in Firefox Console?

### ISSUE THREAD

**Issue by lemuba** [WLANThermo-nano/WLANThermo_ESP32_Software#72]
_Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden.

Passwort-Felder sind auf einer unsicheren (http://) Seite vorhanden. Dies ist ein Sicherheitsrisiko, durch das Zugangsdaten gestohlen werden können.

**Comment by sochs** [comment]
SSL ist aktuell über den ESP nicht möglich, die Verbindung zum Webinterface wird also http:// bleiben, und damit auch der Sicherheitshinweis.

Zum anderen kann ich nichts sagen, vielleicht @Phantomias2006

**Comment by sochs** [comment]
#71

**Comment by Phantomias2006** [comment]
Bezüglich zoom und calc:
Das kommt von der chart Library. Aktuell gibt es schon erste beta Versionen der neuen v3 von chart.js. Sobald diese stable ist werden wir die testen, eventuell hat sich das Problem dann von alleine gelöst.
